include ../../Make.inc

LIBDIR=../../lib
INCDIR=../../include
MODDIR=../../modules 
HERE=..

FINCLUDES=$(FMFLAG)$(HERE) $(FMFLAG)$(MODDIR) $(FMFLAG)$(INCDIR) $(PSBLAS_INCLUDES)

MODOBJS=sp3mm_utils_mod.o

all: objs

objs:

lib:

clean: